management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
#management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 8
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
