#---from official website - https://resilience4j.readme.io/docs/getting-started-3
#management.health.circuitbreakers.enabled: true
#management.health.ratelimiters.enabled: true
#
#resilience4j.circuitbreaker:
#  configs:
#    default:
#      registerHealthIndicator: true
#
#
#resilience4j.ratelimiter:
#  configs:
#    default:
#      registerHealthIndicator: true


management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
#management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 8
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
      #exections that is part of failed call
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      #exections that is NOT part of failed call
      ignoreExceptions:
    service3:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 8
      ringBufferSizeInHalfOpenState: 5
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
      #exections that is part of failed call
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      #exections that is NOT part of failed call
      ignoreExceptions: